Optional indexing
biowdl/tasks pull request #247
Opened 2020-09-07 15:56 UTC by cagaser

### Checklist
- [ ] Pull request details were added to CHANGELOG.md
- [ ] `parameter_meta` for each task is up to date.

2020-09-08 12:15 UTC, DavyCats requested changes

2020-09-08 12:15 UTC, DavyCats commented on bcftools.wdl
> +        ~{if indexing then 'bcftools index --tbi ~{outputPath}' else ''}
Have you tested this?

2020-09-08 12:15 UTC, DavyCats commented on bcftools.wdl
> +        dockerImage: {description: "The docker image used for this task. Changing this may result in errors which the developers may choose not to address.", category: "advanced"}
`compressionLevel` is missing

2020-09-10 09:42 UTC, cagaser commented on bcftools.wdl
> +        ~{if indexing then 'bcftools index --tbi ~{outputPath}' else ''}
Yes, it's working

2020-09-15 07:03 UTC, DavyCats approved these changes

2020-09-15 07:05 UTC, merged